### ISSUE TITLE
tcid = 'C++ heap' -> timeout

### ISSUE THREAD

**Issue by alekla01** [OpenTMI/opentmi-pyclient#20]
### Description
- Type: Bug
- Related commit: #17 

tcid='...+...' -> success
tcid='...++...' -> timeout
tcid='...+++...' -> timeout

---------------------------------------------------------------
## Bug

**opentmi-pyclient version**
v0.3.1

**python version**
2.7.12

**Expected Behavior (tcid='Blinky')**
```
2018-06-13 18:26:15,173 - OpenTMI - DEBUG - GET: http://127.0.0.1:3000/api/v0/testcases?tcid=Blinky
2018-06-13 18:26:15,188 - OpenTMI - DEBUG - testcase 'Blinky' exists in DB (5b212a13aeea1600394e6c4f)
2018-06-13 18:26:15,200 - OpenTMI - DEBUG - result uploaded successfully
```

**Actual Behavior (tcid='C++ heap')**
```
2018-06-13 18:26:15,201 - OpenTMI - DEBUG - GET: http://127.0.0.1:3000/api/v0/testcases?tcid=C%2B%2B+heap
2018-06-13 18:26:15,215 - OpenTMI - DEBUG - testcase 'C++ heap' exists in DB (5b212a13aeea1600394e6c52)
2018-06-13 18:26:45,243 - OpenTMI - WARNING - HTTPConnectionPool(host='127.0.0.1', port=3000): Read timed out. (read timeout=30)
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not NoneType
Logged from file client.py, line 240
```

**Comment by jupe** [comment]
Thanks for reporting this. Trying to find some time slot to fix it, but PR’s are also wellcome!

**Comment by jupe** [comment]
hmm, what was exact content for result ? Trying to reproduce with this simple example:
```
client = OpenTmiClient()
result = {
    "tcid": "C++ heap",
    "exec": {
        "verdict": "pass",
    }
}
client.upload_results(result)
```
but it works just fine. Maybe `tcid` doesn't related to this. Message `Read timed out.` sounds more like it related to something else.. More information needed to be able to reproduce & fix possible issue.

**Comment by alekla01** [comment]
**code:**
```
import opentmi_client

client = opentmi_client.create('localhost', 3000, None, None)

results = []


def _upload(tcid, duration):
    result = {
        'exec': {
            'verdict': 'pass',
            'duration': duration,
        },
        'tcid': tcid
    }
    if not client.upload_results(result):
        results.append('tcid: {}, duration: {}, result: fail'.format(tcid, duration))
    else:
        results.append('tcid: {}, duration: {}, result: success'.format(tcid, duration))


_upload('C++ heap', -1)
_upload('C++ heap', 0)
_upload('C++ heap', 0.090000)
_upload('C++ heap', 100)

_upload('Cpp heap', -1)
_upload('Cpp heap', 0)
_upload('Cpp heap', 0.090000)
_upload('Cpp heap', 100)

_upload('C heap', 100)
_upload('C+ heap', 100)
_upload('C+++ heap', 100)
_upload('C++++++++++ heap', 100)

_upload('C++ heap', None)
_upload('Cpp heap', None)


print('\n\n\n')
print('\n'.join(results))
```
**results:**
```
tcid: C++ heap, duration: -1, result: fail
tcid: C++ heap, duration: 0, result: success
tcid: C++ heap, duration: 0.09, result: fail
tcid: C++ heap, duration: 100, result: fail
tcid: Cpp heap, duration: -1, result: success
tcid: Cpp heap, duration: 0, result: success
tcid: Cpp heap, duration: 0.09, result: success
tcid: Cpp heap, duration: 100, result: success
tcid: C heap, duration: 100, result: success
tcid: C+ heap, duration: 100, result: success
tcid: C+++ heap, duration: 100, result: fail
tcid: C++++++++++ heap, duration: 100, result: fail
tcid: C++ heap, duration: None, result: success
tcid: Cpp heap, duration: None, result: success
```

**error (with updated opentmi):**
```
2018-06-14 00:09:37,210 - OpenTMI - WARNING - status_code: 400
2018-06-14 00:09:37,211 - OpenTMI - WARNING - {"error":"Invalid regular expression: /C++ heap/: Nothing to repeat"}
```

**Comment by jupe** [comment]
This is actually backend side issue - when opentmi tries to update test duration, here: https://github.com/OpenTMI/opentmi/blob/645252a266320551fbc9a275ded6570263c2a07b/app/models/testcase.js#L238.

**Comment by jupe** [comment]
fix coming here: https://github.com/OpenTMI/opentmi/pull/174. Free to try out :)

Results from your example:
```
tcid: C++ heap, duration: -1, result: success
tcid: C++ heap, duration: 0, result: success
tcid: C++ heap, duration: 0.09, result: success
tcid: C++ heap, duration: 100, result: success
tcid: Cpp heap, duration: -1, result: success
tcid: Cpp heap, duration: 0, result: success
tcid: Cpp heap, duration: 0.09, result: success
tcid: Cpp heap, duration: 100, result: success
tcid: C heap, duration: 100, result: success
tcid: C+ heap, duration: 100, result: success
tcid: C+++ heap, duration: 100, result: success
tcid: C++++++++++ heap, duration: 100, result: success
tcid: C++ heap, duration: None, result: success
tcid: Cpp heap, duration: None, result: success
2018-06-19 13:51:18,576 - OpenTMI - DEBUG - result uploaded successfully

Process finished with exit code 0
```
